// Dmytro Chesniuk All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace GAS_SlashGameplayTags
{
	/*--- Input Tags ---*/
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	/*--- Player Tags ---*/
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/*--- Enemy Tags ---*/
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	/*--- Shared Tags ---*/
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	
	
	GAS_SLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
}
